# Generated by Django 5.2.8 on 2025-12-15 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consolidated', '0002_inventoryitem_inventorytransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('sw', 'Swahili'), ('en', 'English')], default='sw', max_length=5)),
                ('total_messages', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('context_snapshot', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FecalImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='fecal_samples/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_disease', models.CharField(blank=True, choices=[('HEALTHY', 'Healthy'), ('COCCIDIOSIS', 'Coccidiosis'), ('NEWCASTLE', 'Newcastle Disease'), ('SALMONELLA', 'Salmonellosis'), ('COLIBACILLOSIS', 'Colibacillosis'), ('UNKNOWN', 'Unknown/Uncertain')], max_length=50, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical')], max_length=20, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('veterinary_consultation_required', models.BooleanField(default=False)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('verified_by_vet', models.BooleanField(default=False)),
                ('actual_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('vet_notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consolidated.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fecal Image Analyses',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='ai_chatsess_user_id_19e151_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_chatmess_session_d95756_idx'),
        ),
    ]
