# Generated by Django 5.2.8 on 2025-12-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0002_inventoryitem_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
