# Generated by Django 5.2.8 on 2025-12-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0003_farmerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm where activity occurs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='consolidated.farm'),
        ),
        migrations.AddField(
            model_name='alert',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch related to this alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='consolidated.batch'),
        ),
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device that triggered this alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='consolidated.device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm related to this alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='consolidated.farm'),
        ),
        migrations.AddField(
            model_name='batch',
            name='breed_config',
            field=models.ForeignKey(blank=True, help_text='Associated breed configuration for this batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='consolidated.breedconfiguration'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm this inventory belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='consolidated.farm'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch this recommendation applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='consolidated.batch'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Farmer this recommendation is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='consolidated.farmerprofile'),
        ),
    ]
