# Generated by Django 5.2.8 on 2025-12-26 07:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0004_add_model_relationships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breedconfiguration',
            options={'ordering': ['breed_type', 'breed_name'], 'verbose_name': 'Breed Configuration', 'verbose_name_plural': 'Breed Configurations'},
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='best_for',
            field=models.TextField(blank=True, help_text='Best suited for (commercial, rural, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='body_weight_dual_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body weight at 16-18 weeks for dual-purpose', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='characteristics',
            field=models.TextField(blank=True, help_text='Detailed characteristics', null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='egg_production_dual',
            field=models.IntegerField(blank=True, help_text='Eggs per year for dual-purpose', null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='example_strains',
            field=models.TextField(blank=True, help_text='Example breeds/strains (comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='feed_before_lay_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Feed consumption before point of lay (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='feed_conversion_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FCR - Feed needed for 1kg weight gain', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='feed_efficiency',
            field=models.CharField(blank=True, help_text='Feed efficiency: High, Moderate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='growth_rate_days',
            field=models.CharField(blank=True, help_text="Days to reach market weight (e.g., '28-42')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='growth_speed',
            field=models.CharField(blank=True, help_text='Growth speed: Slow, Moderate, Very Fast', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='hardiness',
            field=models.CharField(blank=True, help_text='Hardiness level: Low, Moderate, High', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='ideal_humidity_range',
            field=models.CharField(blank=True, help_text="Ideal humidity range (e.g., '60-80%')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='ideal_temperature_range',
            field=models.CharField(blank=True, help_text="Ideal temperature range (e.g., '20-24°C')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='laying_duration_weeks',
            field=models.IntegerField(blank=True, help_text='Laying duration in weeks', null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='lighting_requirements_hours',
            field=models.IntegerField(blank=True, help_text='Required hours of light daily', null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='market_age_weeks',
            field=models.CharField(blank=True, help_text='Market age in weeks', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='market_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target market weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='onset_of_lay_weeks',
            field=models.IntegerField(blank=True, help_text='Age when laying begins (weeks)', null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='recommended_housing_system',
            field=models.CharField(blank=True, choices=[('CAGE', 'Cage System'), ('DEEP_LITTER', 'Deep Litter System'), ('FREE_RANGE', 'Free Range System'), ('SEMI_INTENSIVE', 'Semi-Intensive System')], help_text='Best rearing system', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='breedconfiguration',
            name='suitability',
            field=models.TextField(blank=True, help_text='Suitability description', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='age_days',
            field=models.IntegerField(blank=True, help_text='Age in days (for live birds)', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='average_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average weight in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode/QR code for scanning', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Associated batch for live birds', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_birds', to='consolidated.batch'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch/lot number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='consumption_rate_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily consumption rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='course_days',
            field=models.IntegerField(blank=True, help_text='Course duration in days (for medicines)', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='feed_type',
            field=models.CharField(blank=True, help_text='Type of feed (for FEED category)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_emergency_stock',
            field=models.BooleanField(default=False, help_text='Emergency stock item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_iot_device',
            field=models.BooleanField(default=False, help_text='IoT/Smart device'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, help_text='Storage location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requires_refrigeration',
            field=models.BooleanField(default=False, help_text='Requires cold storage'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('DAY_OLD_CHICKS', 'Day-Old Chicks (DOC)'), ('GROWER_BIRDS', 'Grower Birds'), ('BROILERS', 'Broilers'), ('LAYERS', 'Layers'), ('BREEDERS', 'Breeders'), ('PULLETS', 'Pullets'), ('COCKERELS', 'Cockerels'), ('PARENT_STOCK', 'Parent Stock'), ('REPLACEMENT_STOCK', 'Replacement Stock'), ('COMPLETE_FEEDS', 'Complete Feeds'), ('FEED_INGREDIENTS', 'Feed Ingredients (Raw Materials)'), ('VACCINES', 'Vaccines'), ('DRUGS_TREATMENTS', 'Drugs & Treatments'), ('DISINFECTANTS', 'Disinfectants'), ('SUPPLEMENTS', 'Supplements'), ('EGG_TYPES', 'Egg Types'), ('EGG_PACKAGING', 'Egg Packaging'), ('POULTRY_HOUSE_EQUIPMENT', 'Poultry House Equipment'), ('IOT_DEVICES', 'IoT & Smart Devices'), ('BIOSECURITY', 'Biosecurity Items'), ('SANITATION_TOOLS', 'Sanitation Tools'), ('UTILITIES', 'Utilities'), ('CONSUMABLES', 'Consumables'), ('PACKAGING', 'Packaging Materials'), ('STORAGE_EQUIPMENT', 'Storage Equipment'), ('TRANSPORT_EQUIPMENT', 'Transport Equipment'), ('TRANSPORT_CONSUMABLES', 'Transport Consumables'), ('LABOR_EQUIPMENT', 'Labor Equipment'), ('BUSINESS_MATERIALS', 'Business Materials'), ('EMERGENCY_STOCK', 'Emergency Stock'), ('WATER_EQUIPMENT', 'Water Equipment'), ('WATER_TREATMENT', 'Water Treatment'), ('HATCHERY_EQUIPMENT', 'Hatchery Equipment'), ('HATCHERY_SENSORS', 'Hatchery Sensors'), ('WASTE_PRODUCTS', 'Waste Products'), ('FARM_MACHINERY', 'Farm Machinery'), ('FARM_TOOLS', 'Farm Tools'), ('DIGITAL_EQUIPMENT', 'Digital Equipment'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('FINANCIAL_RECORDS', 'Financial Records'), ('VETERINARY_TOOLS', 'Veterinary Tools'), ('FEED_SUPPLEMENTS', 'Feed Supplements')], help_text='Subcategory for better organization', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Associated batch/flock for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='consolidated.batch'),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='average_maturity_days',
            field=models.IntegerField(default=0, help_text='Days to reach maturity'),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='average_weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average adult weight in kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='breed_type',
            field=models.CharField(choices=[('LAYER', 'Layer'), ('BROILER', 'Broiler'), ('DUAL_PURPOSE', 'Dual-Purpose/Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='eggs_per_year',
            field=models.IntegerField(default=0, help_text='Expected eggs per year'),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='feed_consumption_daily_grams',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily feed consumption in grams', max_digits=10),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='humidity_max_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum humidity percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='humidity_min_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum humidity percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='production_lifespan_days',
            field=models.IntegerField(default=0, help_text='Total production lifespan in days'),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='space_requirement_sqm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Space requirement per bird in sqm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='temperature_max_celsius',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum temperature in Celsius', max_digits=5),
        ),
        migrations.AlterField(
            model_name='breedconfiguration',
            name='temperature_min_celsius',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum temperature in Celsius', max_digits=5),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('LIVE_BIRDS', 'Live Bird Inventory'), ('FEED', 'Feed Inventory'), ('MEDICINE', 'Medicine & Veterinary Inventory'), ('SUPPLEMENTS', 'Supplements & Additives'), ('EGGS', 'Egg Production Inventory'), ('EQUIPMENT', 'Housing & Farm Equipment'), ('SANITATION', 'Farm Sanitation & Biosecurity'), ('UTILITIES', 'Utilities & Consumables'), ('STORAGE', 'Storage & Packaging'), ('TRANSPORT', 'Transport & Logistics'), ('LABOR', 'Labor & Operational Items'), ('SALES', 'Sales & Business Inventory'), ('EMERGENCY', 'Disease & Emergency Stock'), ('WATER', 'Water & Drinking System'), ('HATCHERY', 'Hatchery Inventory'), ('WASTE', 'Waste & By-Products'), ('MACHINERY', 'Machinery & Tools'), ('OFFICE', 'Office & Digital Inventory'), ('FINANCIAL', 'Financial & Records Inventory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Stock In (Purchase)'), ('USAGE', 'Stock Out (Usage)'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return'), ('WASTE', 'Wastage')], max_length=20),
        ),
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=2, help_text="Quantity consumed in item's unit", max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at time of consumption', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost (auto-calculated)', max_digits=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of consumption')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about consumption', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_consumption', to='consolidated.batch')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_consumption_records', to='consolidated.inventoryitem')),
                ('transaction', models.ForeignKey(blank=True, help_text='Link to inventory transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_consumption', to='consolidated.inventorytransaction')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['batch', 'date'], name='consolidate_batch_i_2a886b_idx'), models.Index(fields=['inventory_item', 'date'], name='consolidate_invento_4b46e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRY_WARNING', 'Expiry Warning'), ('EXPIRED', 'Expired'), ('OUT_OF_STOCK', 'Out of Stock'), ('HIGH_CONSUMPTION', 'High Consumption Rate')], max_length=20)),
                ('message', models.CharField(help_text='Human-readable alert message', max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='consolidated.inventoryitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'is_resolved'], name='consolidate_item_id_918e69_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='consolidate_alert_t_2eaf67_idx')],
            },
        ),
    ]
