# Generated by Django 5.2.8 on 2025-12-26 15:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0006_add_health_record_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('DAY_OLD_CHICKS', 'Day-Old Chicks (DOC)'), ('GROWER_BIRDS', 'Grower Birds'), ('BROILERS', 'Broilers'), ('LAYERS', 'Layers'), ('BREEDERS', 'Breeders'), ('PULLETS', 'Pullets'), ('COCKERELS', 'Cockerels'), ('PARENT_STOCK', 'Parent Stock'), ('REPLACEMENT_STOCK', 'Replacement Stock'), ('COMPLETE_FEEDS', 'Complete Feeds'), ('FEED_INGREDIENTS', 'Feed Ingredients (Raw Materials)'), ('CHICK_STARTER_MASH', 'Chick Starter Mash'), ('GROWER_MASH', 'Grower Mash'), ('LAYER_MASH', 'Layer Mash'), ('FINISHER_FEED', 'Finisher Feed'), ('BROILER_CONCENTRATE', 'Broiler Concentrate'), ('PREMIX', 'Premix'), ('CRUSHED_MAIZE', 'Crushed Maize'), ('SOYA_MEAL', 'Soya Meal'), ('FISH_MEAL', 'Fish Meal'), ('VACCINES', 'Vaccines'), ('DRUGS_TREATMENTS', 'Drugs & Treatments'), ('DISINFECTANTS', 'Disinfectants'), ('SUPPLEMENTS', 'Supplements'), ('EGG_TYPES', 'Egg Types'), ('EGG_PACKAGING', 'Egg Packaging'), ('POULTRY_HOUSE_EQUIPMENT', 'Poultry House Equipment'), ('IOT_DEVICES', 'IoT & Smart Devices'), ('BIOSECURITY', 'Biosecurity Items'), ('SANITATION_TOOLS', 'Sanitation Tools'), ('UTILITIES', 'Utilities'), ('CONSUMABLES', 'Consumables'), ('BEDDING', 'Bedding Materials (Sawdust, Rice Husks)'), ('LIME', 'Lime/Disinfectant Powder'), ('CLEANING_MATERIALS', 'Cleaning Materials'), ('FUEL', 'Fuel/Energy'), ('WATER_BILLS', 'Water Bills/Utilities'), ('ELECTRICITY', 'Electricity/Power'), ('PACKAGING', 'Packaging Materials'), ('STORAGE_EQUIPMENT', 'Storage Equipment'), ('TRANSPORT_EQUIPMENT', 'Transport Equipment'), ('TRANSPORT_CONSUMABLES', 'Transport Consumables'), ('LABOR_EQUIPMENT', 'Labor Equipment'), ('EGG_TYPES', 'Egg Types'), ('EGG_PACKAGING', 'Egg Packaging'), ('POULTRY_HOUSE_EQUIPMENT', 'Poultry House Equipment'), ('IOT_DEVICES', 'IoT & Smart Devices'), ('BIOSECURITY', 'Biosecurity Items'), ('SANITATION_TOOLS', 'Sanitation Tools'), ('UTILITIES', 'Utilities'), ('CONSUMABLES', 'Consumables'), ('PACKAGING', 'Packaging Materials'), ('STORAGE_EQUIPMENT', 'Storage Equipment'), ('TRANSPORT_EQUIPMENT', 'Transport Equipment'), ('TRANSPORT_CONSUMABLES', 'Transport Consumables'), ('LABOR_EQUIPMENT', 'Labor Equipment'), ('BUSINESS_MATERIALS', 'Business Materials'), ('EMERGENCY_STOCK', 'Emergency Stock'), ('WATER_EQUIPMENT', 'Water Equipment'), ('WATER_TREATMENT', 'Water Treatment'), ('HATCHERY_EQUIPMENT', 'Hatchery Equipment'), ('HATCHERY_SENSORS', 'Hatchery Sensors'), ('WASTE_PRODUCTS', 'Waste Products'), ('FARM_MACHINERY', 'Farm Machinery'), ('FARM_TOOLS', 'Farm Tools'), ('DIGITAL_EQUIPMENT', 'Digital Equipment'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('FINANCIAL_RECORDS', 'Financial Records'), ('VETERINARY_TOOLS', 'Veterinary Tools'), ('FEED_SUPPLEMENTS', 'Feed Supplements')], help_text='Subcategory for better organization', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EggInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_date', models.DateField()),
                ('grade', models.CharField(choices=[('SMALL', 'Small (< 50g)'), ('MEDIUM', 'Medium (50-60g)'), ('LARGE', 'Large (60-70g)'), ('EXTRA_LARGE', 'Extra Large (> 70g)')], max_length=15)),
                ('quality', models.CharField(choices=[('GRADE_A', 'Grade A (Premium)'), ('GRADE_B', 'Grade B (Standard)'), ('GRADE_C', 'Grade C (Below Standard)'), ('SPOILED', 'Spoiled/Cracked')], max_length=10)),
                ('quantity_trays', models.DecimalField(decimal_places=2, help_text='Number of trays (30 eggs/tray)', max_digits=10)),
                ('quantity_pieces', models.IntegerField(help_text='Individual eggs')),
                ('spoiled_count', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(help_text='Current available stock in pieces')),
                ('price_per_tray', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_inventory', to='consolidated.batch')),
            ],
            options={
                'verbose_name': 'Egg Inventory',
                'verbose_name_plural': 'Egg Inventories',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='EggSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_type', models.CharField(choices=[('RETAIL', 'Retail Customer'), ('WHOLESALE', 'Wholesale'), ('RESTAURANT', 'Restaurant/Hotel'), ('SUPERMARKET', 'Supermarket'), ('DISTRIBUTOR', 'Distributor')], max_length=20)),
                ('quantity_sold', models.IntegerField(help_text='Quantity in pieces')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per piece or tray', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PARTIAL', 'Partial Payment'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('egg_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='consolidated.egginventory')),
            ],
            options={
                'verbose_name': 'Egg Sale',
                'verbose_name_plural': 'Egg Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(choices=[('FEEDER', 'Feeders'), ('DRINKER', 'Drinkers'), ('BROODER', 'Brooders'), ('INCUBATOR', 'Incubators'), ('EGG_TRAY', 'Egg Trays'), ('CRATE', 'Crates'), ('WEIGHING_SCALE', 'Weighing Scales'), ('WATER_TANK', 'Water Tanks'), ('HEATER', 'Heaters'), ('FAN', 'Fans/Ventilation'), ('GENERATOR', 'Generator'), ('SPRAYER', 'Sprayers'), ('THERMOMETER', 'Thermometers'), ('HYGROMETER', 'Hygrometers')], max_length=20)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('NEEDS_REPAIR', 'Needs Repair'), ('RETIRED', 'Retired')], default='GOOD', max_length=20)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_lifespan_years', models.DecimalField(decimal_places=1, help_text='Expected lifespan in years', max_digits=5)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('replacement_alert', models.BooleanField(default=False, help_text='Alert when nearing end of lifespan')),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_details', to='consolidated.inventoryitem')),
            ],
            options={
                'verbose_name': 'Equipment Inventory',
                'verbose_name_plural': 'Equipment Inventories',
            },
        ),
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('ABNORMAL_MORTALITY', 'Abnormal Mortality Rate'), ('EGG_DROP', 'Drop in Egg Production'), ('FEED_INTAKE_LOW', 'Low Feed Intake'), ('WATER_INTAKE_HIGH', 'Excessive Water Consumption'), ('WEIGHT_LOSS', 'Weight Loss Detected'), ('DISEASE_OUTBREAK', 'Potential Disease Outbreak')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('detected_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual value that triggered alert', max_digits=10, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold that was exceeded', max_digits=10, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='consolidated.batch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_health_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Alert',
                'verbose_name_plural': 'Health Alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=255)),
                ('worker_type', models.CharField(choices=[('PERMANENT', 'Permanent Staff'), ('CASUAL', 'Casual Labor'), ('CONTRACT', 'Contract Worker')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(help_text='e.g., Farm Manager, Cleaner, Feeder', max_length=100)),
                ('payment_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('wage_amount', models.DecimalField(decimal_places=2, help_text='Wage amount per payment period', max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='consolidated.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_records', to='consolidated.farmerprofile')),
            ],
            options={
                'verbose_name': 'Labor Record',
                'verbose_name_plural': 'Labor Records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_type', models.CharField(blank=True, choices=[('ANTIBIOTIC', 'Antibiotics'), ('VITAMIN', 'Vitamins'), ('DEWORMER', 'Dewormers'), ('ANTI_STRESS', 'Anti-stress Solutions'), ('ELECTROLYTE', 'Electrolytes'), ('DISINFECTANT', 'Disinfectants')], max_length=20, null=True)),
                ('vaccine_type', models.CharField(blank=True, choices=[('NEWCASTLE', 'Newcastle Disease'), ('GUMBORO', 'Gumboro (IBD)'), ('FOWL_POX', 'Fowl Pox'), ('MAREKS', "Marek's Disease"), ('IB_VACCINE', 'Infectious Bronchitis'), ('FOWL_TYPHOID', 'Fowl Typhoid'), ('LASOTA', 'Lasota (Newcastle Booster)'), ('HITCHNER_B1', 'Hitchner B1')], max_length=20, null=True)),
                ('purpose', models.TextField(help_text='Purpose/indication for use')),
                ('dosage', models.CharField(help_text='Recommended dosage (e.g., 1ml per liter)', max_length=255)),
                ('administration_route', models.CharField(choices=[('ORAL', 'Oral/Drinking Water'), ('INJECTION_IM', 'Intramuscular Injection'), ('INJECTION_SC', 'Subcutaneous Injection'), ('EYE_DROP', 'Eye Drop'), ('WING_STAB', 'Wing Stab'), ('SPRAY', 'Spray')], default='ORAL', max_length=20)),
                ('withdrawal_period_days', models.IntegerField(blank=True, help_text='Days before slaughter/egg consumption', null=True)),
                ('storage_temperature', models.CharField(blank=True, help_text='e.g., 2-8°C, Room Temperature', max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_details', to='consolidated.inventoryitem')),
            ],
            options={
                'verbose_name': 'Medicine/Vaccine Inventory',
                'verbose_name_plural': 'Medicine/Vaccine Inventories',
            },
        ),
        migrations.CreateModel(
            name='MedicineAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dosage_given', models.CharField(help_text='Actual dosage administered', max_length=255)),
                ('number_of_birds', models.IntegerField(help_text='Number of birds treated')),
                ('reason', models.TextField(help_text='Reason for administration (disease, prevention, etc.)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_administrations', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_records', to='consolidated.batch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='consolidated.medicineinventory')),
            ],
            options={
                'verbose_name': 'Medicine Administration Record',
                'verbose_name_plural': 'Medicine Administration Records',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('VETERINARY', 'Veterinary Services'), ('TRANSPORT', 'Transport/Logistics'), ('CONSULTATION', 'Consultation Fees'), ('MAINTENANCE', 'Equipment Maintenance'), ('CLEANING', 'Cleaning Services'), ('LABORATORY', 'Laboratory/Testing Services'), ('OTHER', 'Other Services')], max_length=20)),
                ('service_provider', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_expenses', to='consolidated.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_expenses', to='consolidated.farmerprofile')),
            ],
            options={
                'verbose_name': 'Service Expense',
                'verbose_name_plural': 'Service Expenses',
                'ordering': ['-service_date'],
            },
        ),
    ]
