# Generated by Django 5.2.8 on 2026-01-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0007_alter_inventoryitem_subcategory_egginventory_eggsale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=10),
        ),
    ]
