# Generated by Django 5.2.8 on 2026-01-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0008_alter_farmerprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('TZS', 'Tanzanian Shilling')], default='USD', max_length=3),
        ),
    ]
