# Generated by Django 5.2.8 on 2026-01-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0009_add_currency_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Associated batch for this inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='consolidated.batch'),
        ),
    ]
