# Generated by Django 5.2.8 on 2026-01-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidated', '0010_add_batch_tracking_to_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='feed_stage',
            field=models.CharField(blank=True, choices=[('STARTER', 'Starter Feed (1-18 days)'), ('GROWER', 'Grower Feed (19-40 days)'), ('FINISHER', 'Finisher Feed (40+ days)'), ('LAYER', 'Layer Feed'), ('BREEDER', 'Breeder Feed')], help_text='Feed stage based on bird age', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='humidity_requirement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required humidity (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_price_update',
            field=models.DateField(blank=True, help_text='Last price update date', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lead_time_days',
            field=models.IntegerField(default=2, help_text='Lead time in days for replenishment'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacture_date',
            field=models.DateField(blank=True, help_text='Manufacture/production date', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='market_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current market price per unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='order_up_to_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Order-up-to level (S) - target inventory', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quality_grade',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard'), ('ECONOMY', 'Economy')], default='STANDARD', help_text='Quality grade of the item', max_length=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reorder point (s) - when to reorder', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='safety_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Safety stock level', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='service_level_target',
            field=models.DecimalField(decimal_places=2, default=95.0, help_text='Target service level (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='shelf_life_days',
            field=models.IntegerField(blank=True, help_text='Shelf life in days', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum storage temperature (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum storage temperature (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Supplier price per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ventilation_required',
            field=models.BooleanField(default=False, help_text='Requires special ventilation'),
        ),
    ]
